spring:
    data:
        rest:
            basePath: /api
            defaultPageSize: 100
            returnBodyOnCreate: true
            returnBodyOnUpdate: true
    jpa:
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:mysql://101.101.210.104/mysql?characterEncoding=UTF-8&useSSL=false
        username: root
        password: root78()
